package MYSQL;

public class LEVEL1 {
	
	//과일로 만든 아이스크림 고르기
	SELECT A.FLAVOR FROM FIRST_HALF as A JOIN ICECREAM_INFO as B ON A.FLAVOR = B.FLAVOR 
	WHERE A.TOTAL_ORDER > 3000 AND B.INGREDIENT_TYPE LIKE 'fruit_based' ORDER BY TOTAL_ORDER DESC;
	
	//인기있는 아이스크림
	SELECT FLAVOR FROM FIRST_HALF ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID;
	
	//흉부외과 또는 일반외과 의사 목록 출력하기 // LEFT(컬럼, 몇자리)
	SELECT DR_NAME, DR_ID, MCDP_CD, LEFT(HIRE_YMD, 10) FROM DOCTOR WHERE 
	MCDP_CD = "CS" OR MCDP_CD = "GS" ORDER BY 	HIRE_YMD DESC, DR_NAME;
	
}
